### ISSUE TITLE
ISSUE-250: Pulsar-manager sends requests to invalid subdirectory

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-manager#103]
Original Issue: apache/pulsar-manager#250 

---

My config:

```
  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.1.0
    container_name: pulsar-manager
    ports:
      - "9527:9527"
    environment:
      - REDIRECT_HOST=pulsar.XXXX.org
      - REDIRECT_PORT=`443`
      - DRIVER_CLASS_NAME=org.postgresql.Driver
      - URL='jdbc:postgresql://postgres:5432/pulsar'
      - USERNAME=pulsar
      - PASSWORD=pulsar
      - LOG_LEVEL=DEBUG
    command: /bin/sh
```

When i try to navigate anywhere in the manager I see this error:

![Screenshot_20200122_114226](https://user-images.githubusercontent.com/2544251/72891487-4123f980-3d0c-11ea-8281-2c1d63d83f5a.png)

![image](https://user-images.githubusercontent.com/2544251/73015074-45870a00-3e13-11ea-9900-84d2b3a0d8b5.png)

It tries to request data from:

`https://pulsar.XXXX.org/pulsar-manager/admin/v2/clusters?query=%7B%22cluster%22:%22%22,%22page%22:1,%22limit%22:10%7D`

I logged in as pulsar/pulsar user (same details as in database config).

No error is logged on backend, I'm on DEBUG log level.
